### ISSUE TITLE
Does it supports macos platform？

### ISSUE THREAD

**Issue by rangguangyu** [Xpp521/PyHotKey#1]
There was an error using it on the MAC platform。
![图片](https://user-images.githubusercontent.com/5654146/69213127-316a2680-0b9e-11ea-85f2-369148f1633d.png)

**Comment by Xpp521** [comment]
em...I didn't really test it on the MAC OS. But this error shouldn't have happened.
Can you show me your code ?

**Comment by Xpp521** [comment]
I Attempt to fix this bug in v1.2.0. You can update your module.
If this error happen again, turn on the logger, and send the log message to me.

**Comment by rangguangyu** [comment]
![图片](https://user-images.githubusercontent.com/5654146/69396520-76689700-0d1d-11ea-80a3-97418b44e47b.png)

I do nothing but "from PyHotKey import manager, Key", There was an error ! I guess there was a child thread called the main thread method in PyHotKey

**Comment by Xpp521** [comment]
PyHotKey's keyboard listener runs in a seperate thread, and that's how most hot key modules do.
Here are some reference articles:
https://sqa.stackexchange.com/questions/37745/calling-tis-tsm-in-non-main-thread-environment

https://stackoverflow.com/questions/54511742/java-awt-robot-works-strangely-under-macos-mojave

https://www.reddit.com/r/learnjava/comments/bgnhef/macos_mojave_10142_intellij_idea_ce_warning_about/

**Comment by rangguangyu** [comment]
Problem solved! Thank you very much! The property logger can not set no logger

**Comment by Xpp521** [comment]
You're welcome, dude. The logging function will be improved in the next version.
